### ISSUE TITLE
killed

### ISSUE THREAD

**Issue by fatemeh1291374** [fauxneticien/qbe-std_feats_eval#1]
Hello, thanks for publishing your source code.
When executing the script wav-to-w2v2.py with my own database, execution stops and a "killed" error appears. What is the reason? My database is larger than gos-kdl database.

**Comment by fauxneticien** [comment]
Hi @fatemeh1291374 — I suspect it's a resource issue from Docker running out of memory. The transformers are memory intensive, so I only run toy datasets on my local machine. For the full experiments, I use a cloud instance with at least 64 GB of memory (if running on CPU).

**Comment by fatemeh1291374** [comment]
yes that's right. Thank you so much :)
